dist: xenial
language: python
python:
- '3.7'
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - LAMBDA_S3_BUCKET_NAME=auth0-micronaut-template
  - secure: 2VCUFK1tFIrO2AhE1edvtcgDb2B+7tqiUr0sCAO7AL/buU1Szjiaw9HGhYsq3aeMkp5cQlNyqgLjbF/r5JTTrerzDqpUid4qn5VL7C+djJcirZxtvuV5f01pb4vBQHXQULnjTsz8NPDLXc8GHpILCc+6jIvBbHM+Ri0mVkzTU8b0jFGfbmQjzeNPmrdoh8gT/Eh7f2TEi40vXbmeYXzCh05JMhcHhUYGcxpAUX6nD9NfiLUNLjXgSry/873RxJmZFEy7qRvrhusmmFn8WFQKRVRDo6Etvy11QwagpbVpg69bZt0X7TE6jr6I19RtEmVIfh8GY45XDm0Wb/ju9Y1nq8PqRTnsfNY5N8U0Vi1V9P2RR+suezLa2OmwSVR2/frczSdcturgWScZLr6ECeS1yQ6kiPS1uwhKP/hF+34w8vjsUF2dflrFdTyEZpkxKdWNrR197X7lmsAUj3s/Qdye+27fvRLHdV6kTl+HVvdx7frbAOmwsNz5AjtrZGL05mYBfPIVCFgt0us2NemWKQHtKGMtzRSeTQ1st0ie0ibx1S0aqCEOrGYrFrOXg7SA106T06YAfR4G/4dop+5sPlBBTOfRF1/le60khurgIrsuvRWf+iQ98qwaeK3HDVNeNAushK5+4lngZ37W4KRBtTqdM+04DS/PGqfUPLFFZW8l21E=
  - secure: nXsyPW0sz2qJUsVckfvWUBZLqHbq5JnJqWmoBnHGMgNosbVnwweReUwNIEwuia3s6tofNgLjpipUWLL9uCPt8hvkz7apBs3Sb00Tn0erUAQgMjbnC2VGnP0KK5UkaMZ6KNfQhXBAyZQu9c6fAxqkbeAUWPNzd23TDKRtVEUMvn4NQdDvJ8W7lWSofSddnRYOUo8Nio9rLUVD0MFG1cSqYOpFmqgYpstksTvmyKAUDPCfF9leRgJFnGpf2fkv7UOgGMv7jLaKn9HcOuPG+l8oA3Fho/OcytQLeMUo2p34ReMOeyEBWC1nsEsNV3TKDd3vvra0f70qfbd3AZlqSBRlV31RGUw+ik2To3cKlD4PO1flCUek1h5PhAIRAPe3dEzCZIZkaFotre9Ino0v4bhlsAdNQ2l1urq51tXvtnIWnDl8zw/HN5LHUUHTi7xbgtglbJCepU/hPircnXZy812DEKw6N7u/eUZq0BaBt696oLtTPfCItLDHQmflfcGo/GxYLVw1uQhhDNJxfIQm9JI4+g1ebq3+aOAmtO4fXgJGMnEALxQ4bpIKjGD+UthTmZr+1g1s9DZ66mxNcKTCVOlm22YuKHYjzMqm5/1QDfgz0D3rg0vrQb5AVvzc5mHigpdl0C9qwGxS3f7GoXlbKaHseMGS/TRIj48dpRl2M33KYfk=
install:
- python --version
- pip --version
- pip install awscli aws-sam-cli
- export PATH=$PATH:$HOME/.local/bin
script:
- sam validate
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
