AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Micronaut server utilizing proxy requests through API Gateway
# SAM spec: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# SAM is CF, therefore Cloud Formation spec: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
# SAM Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: EDGE
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ivarprudnikov.auth0.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 320
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ApiUrl:
    # here /Prod refers to implicitly created Prod stage
    Description: root endpoint returns app status
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
